"""
curator/pdf_exporter.py
=======================
Converts the generated Markdown awesome list to a styled PDF.

Uses the `markdown` library to render Markdown → HTML, then
`weasyprint` to convert HTML → PDF with GitHub-inspired styling.

Usage (CLI):
    python -m curator --pdf
    python -m curator --pdf --pdf-output my_list.pdf

Usage (Python):
    from curator.pdf_exporter import md_to_pdf
    md_to_pdf(Path("AWESOME.md"))
"""

from __future__ import annotations

import logging
import re
from html import escape
from pathlib import Path
from typing import Optional

import markdown

logger = logging.getLogger(__name__)

# Suppress verbose DEBUG/INFO logs from WeasyPrint and fontTools
logging.getLogger("weasyprint").setLevel(logging.ERROR)
logging.getLogger("weasyprint.progress").setLevel(logging.ERROR)
logging.getLogger("fontTools").setLevel(logging.ERROR)

# ─────────────────────────────────────────────────────────────────────────────
# Badge colour map (mirrors shields.io named colours)
# ─────────────────────────────────────────────────────────────────────────────

_SHIELD_COLORS: dict[str, str] = {
    "blue": "#0075ca",
    "green": "#2ea44f",
    "orange": "#e36209",
    "red": "#d73a49",
    "yellow": "#dbb31e",
    "purple": "#6f42c1",
    "brightgreen": "#3fb950",
    "lightgrey": "#9f9f9f",
    "lightgray": "#9f9f9f",
    "gray": "#9f9f9f",
    "grey": "#9f9f9f",
    "cyan": "#1bc5d0",
    "black": "#333333",
}

# ─────────────────────────────────────────────────────────────────────────────
# PDF stylesheet — GitHub-inspired design
# ─────────────────────────────────────────────────────────────────────────────

_CSS = """
@page {
    margin: 2cm;
    size: A4;

    @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 8pt;
        color: #6a737d;
    }
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Segoe UI Emoji',
                 Helvetica, Arial, 'Noto Color Emoji', 'Apple Color Emoji', sans-serif;
    color: #24292e;
    line-height: 1.6;
    font-size: 10pt;
}

h1 {
    color: #0366d6;
    border-bottom: 2px solid #e1e4e8;
    padding-bottom: 0.4em;
    font-size: 20pt;
    page-break-after: avoid;
}

h2 {
    color: #24292e;
    border-bottom: 1px solid #e1e4e8;
    padding-bottom: 0.3em;
    font-size: 14pt;
    margin-top: 1.5em;
    page-break-after: avoid;
}

h3 {
    font-size: 11pt;
    margin-top: 1em;
    page-break-after: avoid;
}

/* ── Tables ── */
table {
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-size: 9pt;
    page-break-inside: avoid;
}

th {
    background-color: #0366d6;
    color: white;
    padding: 6px 10px;
    text-align: left;
    font-weight: 600;
}

td {
    padding: 5px 10px;
    border: 1px solid #e1e4e8;
    vertical-align: top;
}

tr:nth-child(even) td {
    background-color: #f6f8fa;
}

/* ── Code ── */
code {
    background-color: #f6f8fa;
    border: 1px solid #e1e4e8;
    padding: 1px 5px;
    border-radius: 3px;
    font-family: 'Courier New', 'Consolas', monospace;
    font-size: 0.88em;
}

pre {
    background-color: #f6f8fa;
    border: 1px solid #e1e4e8;
    padding: 1em;
    border-radius: 6px;
    font-size: 0.85em;
    overflow-x: auto;
    page-break-inside: avoid;
}

pre code {
    border: none;
    padding: 0;
    background: transparent;
}

/* ── Links ── */
a {
    color: #0366d6;
    text-decoration: none;
}

/* ── Blockquotes ── */
blockquote {
    border-left: 4px solid #0366d6;
    margin: 0.5em 0;
    padding: 0.3em 1em;
    color: #6a737d;
    font-style: italic;
    background: #f6f8fa;
    border-radius: 0 4px 4px 0;
}

/* ── Dividers ── */
hr {
    border: none;
    border-top: 1px solid #e1e4e8;
    margin: 1.5em 0;
}

/* ── Details/summary ── */
details {
    background: #f6f8fa;
    border: 1px solid #e1e4e8;
    border-radius: 6px;
    padding: 0.5em 1em;
    margin: 1em 0;
}

/* ── Utility ── */
sub, .footer-note {
    color: #6a737d;
    font-size: 8pt;
}

div[align="center"], p[align="center"] {
    text-align: center;
}

/* ── Badge spans (generated by _badge_to_html) ── */
img {
    max-height: 22px;
    vertical-align: middle;
}
"""


# ─────────────────────────────────────────────────────────────────────────────
# Markdown pre-processor for PDF
# ─────────────────────────────────────────────────────────────────────────────

def _badge_to_html(alt_text: str, img_url: str) -> str:
    """
    Convert one shields.io badge image URL to a styled inline HTML span.
    No network requests — colours are looked up from ``_SHIELD_COLORS``.
    """
    _pill = (
        "display:inline-flex;border-radius:3px;overflow:hidden;"
        "font-size:7pt;font-family:monospace;vertical-align:middle;"
        "margin:1px 3px;border:1px solid rgba(0,0,0,0.12);"
    )
    _dark = "background:#555;color:#fff;padding:2px 5px;"
    _val  = "color:#fff;padding:2px 5px;background:{bg};"

    if "awesome.re" in img_url:
        return (
            '<span style="display:inline-block;border-radius:3px;background:#FC60A8;'
            'color:#fff;padding:2px 8px;font-size:7pt;font-family:monospace;'
            'vertical-align:middle;margin:1px 3px;">awesome</span>'
        )

    sm = re.search(r"shields\.io/badge/([^?#]+)", img_url)
    if not sm:
        return (
            f'<span style="background:#555;color:#fff;padding:2px 6px;'
            f'border-radius:3px;font-size:7pt;">{escape(alt_text)}</span>'
        )

    # shields.io uses "--" to represent a literal dash in label/value
    raw   = sm.group(1).replace("--", "\x00")
    parts = [p.replace("\x00", "-") for p in raw.split("-")]

    if len(parts) >= 3 and parts[-1].lower() in _SHIELD_COLORS:
        label = "-".join(parts[:-2])
        value = parts[-2]
        bg    = _SHIELD_COLORS[parts[-1].lower()]
        lbl   = f'<span style="{_dark}">{escape(label)}</span>' if label else ""
        val   = f'<span style="{_val.format(bg=bg)}">{escape(value)}</span>'
        return f'<span style="{_pill}">{lbl}{val}</span>'

    if len(parts) >= 2 and parts[-1].lower() in _SHIELD_COLORS:
        content = "-".join(parts[:-1])
        bg      = _SHIELD_COLORS[parts[-1].lower()]
        return f'<span style="{_pill}"><span style="{_val.format(bg=bg)}">{escape(content)}</span></span>'

    return (
        f'<span style="background:#555;color:#fff;padding:2px 6px;'
        f'border-radius:3px;font-size:7pt;">{escape(alt_text)}</span>'
    )


def _clean_for_pdf(md_text: str) -> str:
    """
    Pre-process Markdown for clean PDF rendering:

    1. Convert ``[![alt](shields_url)](link)`` badges to styled HTML spans
       (no external requests; colours are resolved from ``_SHIELD_COLORS``).
    2. Replace ⭐ (U+2B50) with ★ (U+2605, available in all standard fonts)
       and strip remaining Supplementary Multilingual Plane emoji that
       render as □ boxes in PDF.
    3. Strip relative file links (e.g. ``[text](CONTRIBUTING.md)``) to plain
       text — prevents ERR_FILE_NOT_FOUND when opening the PDF in Chrome.
       Absolute ``https://`` links and ``#anchor`` links are kept intact.
    4. Remove ``<div>``/``</div>`` wrapper tags so the markdown library
       does not treat the centre-aligned header block as raw HTML.
    5. Collapse excess blank lines.
    """
    # ── 1. Badges → styled <span> elements (no href, no ERR_FILE_NOT_FOUND) ───
    _badge_re = re.compile(r'\[!\[([^\]]*)\]\(([^)]+)\)\]\([^)]*\)')

    def _sub_badge(m: re.Match) -> str:
        return _badge_to_html(m.group(1), m.group(2))

    # Collect consecutive badge-only lines into one inline row
    lines: list[str] = md_text.splitlines()
    out:   list[str] = []
    pending: list[str] = []

    def _flush() -> None:
        if pending:
            out.append(" ".join(pending))
            pending.clear()

    for line in lines:
        if _badge_re.search(line) and not _badge_re.sub("", line).strip():
            # Line contains ONLY badge(s)
            pending.extend(_badge_to_html(m.group(1), m.group(2))
                           for m in _badge_re.finditer(line))
        else:
            _flush()
            out.append(_badge_re.sub(_sub_badge, line))
    _flush()
    md_text = "\n".join(out)

    # ── 2. Emoji fixes ────────────────────────────────────────────────────────
    md_text = md_text.replace("\u2B50", "")                # strip ⭐ (no emoji fonts in PDF)
    md_text = re.sub(r"[\U0001F000-\U0001FFFF]", "", md_text)  # strip SMP emoji
    md_text = re.sub(r"[\uFE00-\uFE0F]", "", md_text)     # strip variation selectors

    # ── 3. Relative links → plain text ───────────────────────────────────────
    def _fix_link(m: re.Match) -> str:
        text, href = m.group(1), m.group(2)
        if href.startswith(("http://", "https://", "#")):
            return m.group(0)   # keep absolute & anchor links
        return text              # strip href from relative local-file links

    md_text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', _fix_link, md_text)

    # ── 4. Remove <div> / </div> wrappers ────────────────────────────────────
    md_text = re.sub(r"</?div[^>]*>", "", md_text, flags=re.IGNORECASE)

    # ── 5. Collapse 3+ consecutive blank lines into 2 ─────────────────────────
    return re.sub(r"\n{3,}", "\n\n", md_text)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────


def md_to_pdf(
    md_path: Path,
    pdf_path: Optional[Path] = None,
) -> Path:
    """
    Convert a Markdown file to a styled PDF document.

    Parameters
    ----------
    md_path:
        Path to the source ``.md`` file (e.g. ``AWESOME.md``).
    pdf_path:
        Destination path for the PDF. Defaults to the same directory
        and filename as *md_path* with a ``.pdf`` extension.

    Returns
    -------
    Path
        The path where the PDF was written.

    Raises
    ------
    FileNotFoundError
        If *md_path* does not exist.
    """
    if not md_path.exists():
        raise FileNotFoundError(f"Markdown source not found: {md_path}")

    out_path = pdf_path or md_path.with_suffix(".pdf")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Converting Markdown → PDF: %s → %s", md_path, out_path)

    md_text = md_path.read_text(encoding="utf-8")

    # Strip badges and bare HTML wrappers before converting
    md_text = _clean_for_pdf(md_text)

    _md_to_pdf_weasyprint(md_text, out_path, md_path.parent, md_path.stem)

    size_kb = out_path.stat().st_size / 1024
    logger.info("PDF written → %s (%.1f KB)", out_path.resolve(), size_kb)
    return out_path


def _md_to_pdf_weasyprint(md_text: str, out_path: Path, base_dir: Path, title: str) -> None:
    """Render cleaned markdown to PDF via markdown + weasyprint."""
    # Import lazily so markdown cleanup logic can be unit-tested
    # without requiring the full PDF backend in the test environment.
    from weasyprint import CSS, HTML

    # Render Markdown → HTML with GitHub-compatible extensions
    html_body = markdown.markdown(
        md_text,
        extensions=[
            "tables",       # GitHub-style | pipe | tables
            "fenced_code",  # ```fenced code blocks```
            "toc",          # [TOC] auto table of contents
            "nl2br",        # Preserve single newlines as <br>
            "sane_lists",   # Better nested list handling
            "attr_list",    # {: .class } attribute syntax
            "md_in_html",   # Process Markdown inside HTML blocks (e.g. <div>)
        ],
    )

    # Wrap in a minimal full HTML document
    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
</head>
<body>
{html_body}
</body>
</html>"""

    # base_url lets weasyprint resolve relative image paths
    HTML(string=html_doc, base_url=str(base_dir)).write_pdf(
        target=str(out_path),
        stylesheets=[CSS(string=_CSS)],
    )
